on:
  push:
    branches:
    - main
    - release
jobs:
  test:
    name: Test on latest Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install -y gzip openssl pigz pv xdelta3 shunit2
    - name: run tests
      run: tests/test.sh
      
